version: '3.9'

services:
  db:
    image: postgres:16
    container_name: product-nest-db
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local